# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-11 22:33
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('song', models.CharField(max_length=72)),
                ('upvotes', models.IntegerField(default=1)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('song', models.CharField(max_length=72, unique=True)),
                ('upvotes', models.IntegerField(default=1)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2016, 3, 11, 22, 33, 31, 959214))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2016, 3, 11, 22, 33, 31, 959248))),
                ('minutes', models.IntegerField(default='1')),
                ('seconds', models.IntegerField(default='1')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
