# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-26 02:51
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('song', models.CharField(max_length=72)),
                ('upvotes', models.IntegerField(default=1)),
                ('title', models.CharField(default='Pre-update request', max_length=100)),
                ('minutes', models.IntegerField(default='1')),
                ('seconds', models.IntegerField(default='1')),
                ('favorites', models.ManyToManyField(related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('song', models.CharField(max_length=72, unique=True)),
                ('upvotes', models.IntegerField(default=1)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2016, 3, 26, 2, 51, 47, 947245))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2016, 3, 26, 2, 51, 47, 947279))),
                ('minutes', models.IntegerField(default='1')),
                ('seconds', models.IntegerField(default='1')),
                ('title', models.CharField(default='None', max_length=100)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
