# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-17 22:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160317_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='title',
            field=models.CharField(default='Pre-update request', max_length=100),
        ),
        migrations.AlterField(
            model_name='songs',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 17, 22, 45, 4, 908547)),
        ),
        migrations.AlterField(
            model_name='songs',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 17, 22, 45, 4, 908512)),
        ),
        migrations.AlterField(
            model_name='songs',
            name='title',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
