# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_songs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songs',
            options={'ordering': ('-created',)},
        ),
    ]
