# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-26 03:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160326_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 26, 3, 2, 53, 157776)),
        ),
        migrations.AlterField(
            model_name='songs',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 26, 3, 2, 53, 157743)),
        ),
    ]
