# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-26 03:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20160326_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 26, 3, 3, 10, 336330)),
        ),
        migrations.AlterField(
            model_name='songs',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 26, 3, 3, 10, 336296)),
        ),
    ]
