# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-26 03:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20160326_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='favorites',
        ),
        migrations.AlterField(
            model_name='songs',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 26, 3, 8, 25, 637271)),
        ),
        migrations.AlterField(
            model_name='songs',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 26, 3, 8, 25, 637227)),
        ),
    ]
