# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20160306_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='song',
            field=models.CharField(default=None, max_length=72, unique=True),
        ),
    ]
