# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-18 21:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20160318_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='minutes',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='archive',
            name='seconds',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 18, 21, 35, 45, 965438)),
        ),
        migrations.AlterField(
            model_name='songs',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 18, 21, 35, 45, 965404)),
        ),
    ]
