# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-15 00:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20160311_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='next',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 15, 0, 50, 50, 86155)),
        ),
        migrations.AlterField(
            model_name='songs',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 15, 0, 50, 50, 86121)),
        ),
    ]
