# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-22 20:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20160318_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 22, 20, 34, 16, 63877)),
        ),
        migrations.AlterField(
            model_name='songs',
            name='minutes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='songs',
            name='seconds',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='songs',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 22, 20, 34, 16, 63841)),
        ),
    ]
