# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-15 01:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20160315_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='next',
        ),
        migrations.AlterField(
            model_name='songs',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 15, 1, 13, 19, 798980)),
        ),
        migrations.AlterField(
            model_name='songs',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 15, 1, 13, 19, 798946)),
        ),
    ]
