# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20160306_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='owner',
        ),
    ]
