# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-26 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20160326_0308'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='posts.Archive'),
        ),
    ]
